### PR TITLE
Try updating conda-build to fix CI issue

### PR DESCRIPTION
**Pull request by paulromano**
Our weekly CI tests have been [failing](https://github.com/openmc-dev/openmc-notebooks/actions) for the last few weeks. This is an attempt to get them working again based on suggestions [here](https://github.com/mamba-org/mamba/issues/1583).

### CODE REVIEW

**Comment by paulromano** [comment]
Well, looks like the original install error relating to conda/mamba is fixed, but now there's actually a failure on the C API notebook. Not sure why it's [failing to find materials.xml](https://github.com/openmc-dev/openmc-notebooks/actions/runs/3810483152/jobs/6482587992)... any ideas @pshriwise?

**Comment by pshriwise** [comment]
The solution to this turned out to be relatively simple, but the reason is somewhat convoluted.

To get things working we just need to update the path to the cross sections from `$HOME/endfb71_hdf5/cross_sections.xml`  to `$HOME/endfb-vii.1-hdf5/cross_sections.xml` in the CI file.

I found that the reason for this is that errors occur when using material features that use some of that cross section info (like setting enrichment or using `add_element`). This is what was causing the CAPI test to fail. We should probably remove `allow_errors=True` from this line to catch things like this more clearly:

```
    ep = ExecutePreprocessor(timeout=600,
                             kernel_name='python3',
                             allow_errors=True)
````

It was strange to me that the other tests _weren't_ failing. I'm not entirely sure why TB. My guess is that it has to do with the CI cache of the cross section data being available only at certain times during execution, but I'm really not sure.

I'll also note that using [tmate](https://github.com/marketplace/actions/debugging-with-tmate) was really helpful in debugging this. Definitely going to be using that track down other CI issues in the future. 🚀

**Comment by paulromano** [comment]
Ah, duh, the cross sections problem is my fault :man_facepalming: Thanks for digging into that! I just updated that along with removing `allow_errors=True`.

**Review by pshriwise — APPROVED** [review]
Looks good! Thanks for the updates @paulromano!

**Comment by pshriwise** [comment]
Oh, dangit. I thought it was showing passing tests when I approved... It looks like there are some dependencies we need to install in CI...

**Comment by paulromano** [comment]
Now I'm confused... how did it ever pass if we were missing dependencies?

**Comment by pshriwise** [comment]
Seems like it was directly related to `allow_errors=True`. Though I do recall catching runtime errors previously... Maybe only certain exceptions were making it through?

**Comment by paulromano** [comment]
Sounds good -- do you want me to revert the `allow_errors` change for now and then we can fix the dependencies in a separate PR? Most of the dependencies will be easy to handle but one of the notebooks requires OpenMOC, which will be more of a challenge.

**Comment by pshriwise** [comment]
Yeah, I think reverting that change is fine for now. I just about have the OpenMOC bit taken care of I think, but I can submit that separately.

**Pull request merged**
